  version: '3.8'

  services:
    app:
      build: .
      ports:
        - "5000:5000"
      environment:
        - DATABASE_URL=postgres://postgres:postgres@db:5432/git_security_analyzer
        - NODE_ENV=development
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - OPENAI_API_VERSION=${OPENAI_API_VERSION}
        - OPENAI_API_BASE=${OPENAI_API_BASE}
        - PGUSER=postgres
        - PGPASSWORD=postgres
        - PGHOST=db
        - PGPORT=5432
        - PGDATABASE=git_security_analyzer
      depends_on:
        db:
          condition: service_healthy
      volumes:
        - .:/app
        - /app/node_modules
      command: npm run dev

    db:
      image: postgres:16
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=git_security_analyzer
        - PGUSER=postgres
        - PGPASSWORD=postgres
        - PGDATABASE=git_security_analyzer
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d git_security_analyzer"]
        interval: 5s
        timeout: 5s
        retries: 5

  volumes:
    postgres_data: